### ISSUE TITLE
Title looks funky on subpages

### ISSUE THREAD

**Issue by fuglede** [cryptopartydk/cryptoparty.dk#15]
Since there is currently no delimiter in [/templates/base.html#L14](https://github.com/cryptopartydk/cryptoparty.dk/blob/master/cryptoparty/templates/base.html#L14), the title looks a bit goofy on various subpages. Perhaps remove "Cryptoparty.dk" from the title in <code>base.html</code> and only add it to <code>frontpage.html</code> instead?

**Comment by valberg** [comment]
Ah, yes. I'd rather we add a `|` to the title in `base.html`. Then it's always clear in tabs that it's the particular site. Maybe even over engineer it a bit so the site name is taken from `django.contrib.sites` (https://docs.djangoproject.com/en/1.8/ref/contrib/sites/) or even from a setting (I'd maybe prefer the former, since that seems to be "the django way").

**Comment by fuglede** [comment]
Also good. And then just give <code>frontpage.html</code> a name as well, so the title doesn't become "Cryptoparty.dk |" in that case?
